### ISSUE TITLE
Icon Grafik is not visible

### ISSUE THREAD

**Issue by dreschpe** [TheAntTeam/TheAntFarm#15]
**Describe the bug**
I run TheAntFarm with windows11, Python 3.9.12
After start, the program is working, but all button graphics are not shown.
Only the text.

**Screenshots**
![ant](https://user-images.githubusercontent.com/6898010/163404969-811a65b2-f9c7-433e-a1c6-35c9e5127ba2.jpg)

**Comment by TheAntTeam** [comment]
Hi,
are you launching the python main script from the project folder?

**Comment by dreschpe** [comment]
Yes, I was launching it from the project folder.
I have switched to the second option with visual code and there I can see the graphics :-)

**Comment by TheAntTeam** [comment]
Hello @dreschpe,
is the issue solved with the commit here above? If so, I would close the issue, otherwise we investigate further :)

**Comment by dreschpe** [comment]
Unfortunately, the bug is still there.
I pull the actual code and follow the steps.
If I start it inside visual code it is working.

**Comment by TheAntTeam** [comment]
Hi, did you activate the virtual env before starting the program? We are trying to reproduce the issue, but we are not able up to now.

**Comment by dreschpe** [comment]
Yes I'm following all steps ...

Python 3.9.13
Win 11 Pro

**Comment by TheAntTeam** [comment]
Ok, thank you, I was guessing that there was the resource path not correctly set for some reason, that's why I asked about the venv.  
  
If you can do it, one more test would be to re-build the resources.   
This can be done, if you have the pyside2-tools installed. on the terminal with this command:  

> .\build.py ui  

or with the following command:

pyside2-rcc app_resources.qrc -o app_resources_rc.py  
  
In the meanwhile we try to set up a window 11 machine to reproduce all the conditions.

**Comment by alexlinno** [comment]
Hi I have the same issue, even running it from VS code. I see that I'm in venv and tried to rebuild (both ways) but still have the problem
W10 and Python 3,10

**Comment by alexlinno** [comment]
after deinstalling and installing it all again I got the icons:-)

**Comment by TheAntTeam** [comment]
Hi @alexlinno,
nice to know👍 
When you say "deinstalling and installing it all again" you mean that you re-did the whole installation process?
Do you know what could be different respect from the first installation?

**Comment by dreschpe** [comment]
The bug is back, also with VS Code.
I can re-build the resources. It works. I have renamed one of the graphics and it fails.
The new file is built. The only graphic used by the program is the logo. 
Also, the newly built file is used. If I kill it the program does not start.
No idea ...

**Comment by TheAntTeam** [comment]
>  I have renamed one of the graphics and it fails. The new file is built. The only graphic used by the program is the logo. Also, the newly built file is used. If I kill it the program does not start. No idea ...

Hi @dreschpe.
The "app_resources.qrc" file contains the lists of relative paths to the files used, if you changed the name or the relative path of a file also this file should be updated and then re-built into the "app_resources_rc.py" file.
Let us know if this solves the issue.

**Comment by dreschpe** [comment]
The logo is a png file and is displayed. I can edit it and it is loaded.
The other graphics are svg files and they are not displayed.
Is there a problem with the component which is displaying the svg's ?
I'm no QT programmer, but I think if the path to the logo is working, also the path to the icons will work.
.

**Comment by TheAntTeam** [comment]
Closing this old issue, likely it was due to the regeneration of the resource py not done or not done properly.
